# @url https://docs.docker.com/compose/yml/
# @cli docker run --privileged --rm -it mgcrea/unifi-video /bin/bash
# @cli docker-compose run unify_video_controller /bin/bash

version: '2'
services:
  unify_video_controller:
    image: mgcrea/unifi-video:3
    container_name: unify_video_controller
    environment:
      - TZ=Europe/Paris
    network_mode: "bridge"
    privileged: true # @TODO SYS_ADMIN, DAC_READ_SEARCH, NET_BIND_SERVICE, SYS_PTRACE, SETUID, and SETGID
    volumes:
      - ./data/lib:/var/lib/unifi-video
      - ./data/log:/var/log/unifi-video
      - ./data/work:/usr/lib/unifi-video/work
    ports:
      - "7080:7080/tcp"
      - "7443:7443/tcp"
      - "6666:6666"
      - "7447:7447"
    restart: always
